version: '3.8'

services:
  my-python-app:
    image: lijozech12/weather-fetcher:latest
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_DEFAULT_REGION}

