apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30083
