name: Build and Push Docker images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-context:
          - '.'
          - './subdir'
        include:
          - docker-context: '.'
            image-name: 'lijozech12/weather-app'
          - docker-context: './weather-app'
            image-name: 'lijozech12/weather-fetcher'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.docker-context }}
        file: ${{ matrix.docker-context }}/Dockerfile
        push: true
        tags: ${{ matrix.image-name }}:latest
